<?php

return [
    'update_sections' => [
        'static_fleet' => [
            'title' => 'Struktur və texnika siyahısı',
            'dashboard_section' => null,
            'manual' => 'Parametrlər -> Texnikaları sinxronlaşdır',
            'auto' => 'Gündəlik 00:00 paketində texnika və geofence siyahısı yenilənir.',
            'wialon_command' => 'fleet:sync-units / fleet:sync-geofences',
            'local_tables' => 'equipments, equipment_types, projects, project_wialon_groups, geofences',
        ],
        'daily_averages' => [
            'title' => 'Orta motosaat / Orta yürüş',
            'dashboard_section' => 'daily_averages',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Orta motosaat göstəricisi / Orta yürüş göstəricisi',
            'auto' => 'Gündəlik 00:00-da dünənki və seçilmiş əvvəlki günlər yenilənir.',
            'wialon_command' => 'fleet:sync-report-stats + fleet:aggregate-daily',
            'local_tables' => 'equipment_daily_stats, daily_unit_aggregates',
        ],
        'top_working_units' => [
            'title' => 'Top 20 az işləyənlər / Top 20 çox işləyənlər',
            'dashboard_section' => 'top_working_units',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Top 20 az işləyənlər / Top 20 çox işləyənlər',
            'auto' => 'Gündəlik 00:00 paketində Wialon Engine hours report yenilənir.',
            'wialon_command' => 'fleet:sync-engine-hours-report',
            'local_tables' => 'engine_hours_report_unit_days, wialon_report_sync_items',
        ],
        'geofence_outside' => [
            'title' => 'Geofence Transferləri',
            'dashboard_section' => 'geofence_outside',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Geofence Transferləri',
            'auto' => 'Gündəlik 00:00 paketində dünənki geozon api intervalı yenilənir.',
            'wialon_command' => 'fleet:sync-geozon-api',
            'local_tables' => 'unit_foreign_geofence_intervals',
        ],
        'shift_efficiency' => [
            'title' => 'Effektivlik və shift hesabatı',
            'dashboard_section' => null,
            'manual' => 'Tarixi məlumatların yenilənməsi hazırda bu bölməni ayrıca seçmir; gecə paketində işləyir.',
            'auto' => 'Gündəlik 00:00 paketində plan-shift-sync və run-shift-sync icra olunur.',
            'wialon_command' => 'fleet:plan-shift-sync + fleet:run-shift-sync',
            'local_tables' => 'equipment_daily_stats, wialon_report_sync_items',
        ],
    ],

    'shared_bindings' => [
        [
            'title' => 'Project binding',
            'description' => 'Layihə və ownership Wialon qrupuna project_wialon_groups cədvəli ilə bağlanır.',
            'items' => [
                'projects.id -> project_wialon_groups.project_id',
                'project_wialon_groups.ownership_type -> NWC / ICARE',
                'project_wialon_groups.wialon_group_id -> Wialon qrup ID',
            ],
        ],
        [
            'title' => 'Geofence binding',
            'description' => 'Layihə geozonaları Wialon geofence ID ilə bağlanır. Bir layihədə bir neçə geofence ola bilər.',
            'items' => [
                'geofences.project_id -> projects.id',
                'geofences.wialon_geofence_id -> Wialon geofence ID',
                'Wialon geofence group istifadə olunmur',
            ],
        ],
        [
            'title' => 'Dashboard filters',
            'description' => 'Dashboard, modal və Excel eyni filter kontekstini istifadə etməlidir.',
            'items' => [
                'date_from / date_to',
                'project_id',
                'ownership_type',
                'equipment_type_id',
                'status / current_geozone_key',
            ],
        ],
    ],

    'widgets' => [
        [
            'key' => 'ownership-share',
            'title' => 'NWC və İCARƏ payı',
            'purpose' => 'Layihələrə bağlı texnikaların ownership üzrə say bölgüsünü göstərir.',
            'dashboard_block' => 'Donut chart + sağ legend',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, project_wialon_groups',
            'service' => 'FleetOwnershipStatsService, DashboardService::getOverview',
            'binding' => 'Yalnız layihələrə bağlı NWC / ICARE qrupları sayılır; +NWC+ və +İcarə+ root qrupları sayılmır.',
            'report_rows' => [
                'equipments.project_wialon_group_id',
                'equipments.matched_wialon_group_id',
                'equipments.ownership_type',
                'equipments.active / excluded_from_dashboard',
            ],
            'click' => 'Sektor kliklənəndə Dashboard drilldown modal ownership filteri ilə açılır.',
            'excel' => 'Dashboard export eyni ownership seçimini istifadə edir.',
        ],
        [
            'key' => 'equipment-types-nwc',
            'title' => 'Texnika növü üzrə: NWC payı',
            'purpose' => 'NWC texnikalarının növ üzrə sayını göstərir.',
            'dashboard_block' => 'Donut chart + növ cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, equipment_types',
            'service' => 'DashboardService::getEquipmentTypeDistributionByOwnership',
            'binding' => 'ownership_type = NWC, project_id filteri varsa yalnız seçilmiş layihə.',
            'report_rows' => [
                'equipment_types.name',
                'COUNT(DISTINCT equipments.id)',
                'equipments.project_id',
                'equipments.ownership_type',
            ],
            'click' => 'Növ sətri/sektoru drilldown modalı equipment_type_id + ownership_type=NWC ilə açır.',
            'excel' => 'equipment-types-nwc block export eyni növ və ownership məntiqini istifadə edir.',
        ],
        [
            'key' => 'equipment-types-icare',
            'title' => 'Texnika növü üzrə: İcarə payı',
            'purpose' => 'İcarə texnikalarının növ üzrə sayını göstərir.',
            'dashboard_block' => 'Donut chart + növ cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, equipment_types',
            'service' => 'DashboardService::getEquipmentTypeDistributionByOwnership',
            'binding' => 'ownership_type = ICARE, project_id filteri varsa yalnız seçilmiş layihə.',
            'report_rows' => [
                'equipment_types.name',
                'COUNT(DISTINCT equipments.id)',
                'equipments.project_id',
                'equipments.ownership_type',
            ],
            'click' => 'Növ sətri/sektoru drilldown modalı equipment_type_id + ownership_type=ICARE ilə açır.',
            'excel' => 'equipment-types-icare block export eyni növ və ownership məntiqini istifadə edir.',
        ],
        [
            'key' => 'project-comparison',
            'title' => 'Layihə üzrə: NWC və İcarə payı',
            'purpose' => 'Hər layihədə NWC və İcarə texnika sayını müqayisə edir.',
            'dashboard_block' => 'Horizontal bar chart + layihə cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, projects',
            'service' => 'DashboardService::getProjectOwnershipComparison',
            'binding' => 'projects.id -> equipments.project_id; ownership_type üzrə iki say sütunu.',
            'report_rows' => [
                'projects.name',
                'COUNT(DISTINCT equipments.id) where ownership_type=NWC',
                'COUNT(DISTINCT equipments.id) where ownership_type=ICARE',
            ],
            'click' => 'Layihə və ownership seçimi ilə drilldown modal açılır.',
            'excel' => 'Dashboard export layihə + ownership saylarını verir.',
        ],
        [
            'key' => 'project-work-categories-nwc',
            'title' => 'Effektivlik: NWC üzrə',
            'purpose' => 'NWC texnikalarının gündüz iş statusunu və ayrıca overtime jurnalını göstərir.',
            'dashboard_block' => 'Donut chart yalnız daytime statusları + sağ status cədvəli',
            'wialon_report' => 'Qrup report novbe 24 saat (api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'FleetEfficiencyService',
            'binding' => 'project_wialon_groups.wialon_group_id üzrə Wialon qrup; ownership_type=NWC.',
            'report_rows' => [
                'Smena 1 / Daytime: 08:00-17:59 -> daytime_hours',
                'Smena 2 / Overtime: 18:00-07:59 -> overtime_hours',
                'day_status categories use daytime_hours only',
                'over_10_hours also includes rows where total_hours > 10',
                'overtime_hours is shown as a separate marker and does not change day_status',
                'has_overtime = overtime_hours > 0',
            ],
            'click' => 'Day status kliklənəndə həmin status; Overtime kliklənəndə overtime_hours > 0 modalı açılır.',
            'excel' => 'Excel daytime status və overtime sütunlarını eyni service ilə çıxarır.',
        ],
        [
            'key' => 'project-work-categories-icare',
            'title' => 'Effektivlik: İcarə üzrə',
            'purpose' => 'İcarə texnikalarının gündüz iş statusunu və ayrıca overtime jurnalını göstərir.',
            'dashboard_block' => 'Donut chart yalnız daytime statusları + sağ status cədvəli',
            'wialon_report' => 'Qrup report novbe 24 saat (api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'FleetEfficiencyService',
            'binding' => 'project_wialon_groups.wialon_group_id üzrə Wialon qrup; ownership_type=ICARE.',
            'report_rows' => [
                'Smena 1 / Daytime: 08:00-17:59 -> daytime_hours',
                'Smena 2 / Overtime: 18:00-07:59 -> overtime_hours',
                'day_status categories use daytime_hours only',
                'over_10_hours also includes rows where total_hours > 10',
                'overtime_hours is shown as a separate marker and does not change day_status',
                'has_overtime = overtime_hours > 0',
            ],
            'click' => 'Day status kliklənəndə həmin status; Overtime kliklənəndə overtime_hours > 0 modalı açılır.',
            'excel' => 'Excel daytime status və overtime sütunlarını eyni service ilə çıxarır.',
        ],
        [
            'key' => 'average-engine-hours',
            'title' => 'Orta motosaat göstəricisi',
            'purpose' => 'Texnika növü və ownership üzrə gündəlik orta motosaatı göstərir.',
            'dashboard_block' => 'Horizontal average bars',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'DashboardDailyAverageService',
            'binding' => 'Layihə + ownership Wialon qrupundan Engine hours sütunu yerli statistikaya yazılır.',
            'report_rows' => [
                'Engine hours -> worked_hours / engine_hours',
                'Texnika adı -> equipment_id match',
                'statistic_date',
                'Formula: SUM(engine_hours) / COUNT(DISTINCT unit_id) / calendar_days',
            ],
            'click' => 'Bar kliklənəndə metric=engine_hours, type, ownership və period ilə modal açılır.',
            'excel' => 'Xülasə və Gündəlik detallar eyni DashboardDailyAverageService seçimini istifadə edir.',
        ],
        [
            'key' => 'average-mileage',
            'title' => 'Orta yürüş göstəricisi',
            'purpose' => 'Dump Truck üçün ownership üzrə gündəlik orta yürüşü göstərir.',
            'dashboard_block' => 'Horizontal average bars',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'DashboardDailyAverageService',
            'binding' => 'Yalnız Dump Truck; mənfi mileage çıxarılır; NULL adi 0 kimi maskalanmır.',
            'report_rows' => [
                'Mileage / distance -> distance_km',
                'Texnika adı -> equipment_id match',
                'statistic_date',
                'Formula: SUM(distance_km) / COUNT(DISTINCT unit_id) / calendar_days',
            ],
            'click' => 'Bar kliklənəndə metric=mileage, type=Dump Truck, ownership və period ilə modal açılır.',
            'excel' => 'Xülasə və Gündəlik detallar eyni DashboardDailyAverageService seçimini istifadə edir.',
        ],
        [
            'key' => 'least-working',
            'title' => 'Top 20 az işləyənlər',
            'purpose' => 'Seçilmiş periodda ən az faktiki motosaatı olan 20 texnikanı göstərir.',
            'dashboard_block' => 'Ranking table',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'engine_hours_report_unit_days',
            'service' => 'TopWorkingUnitsService',
            'binding' => 'parse_status=ok, engine_hours >= 0, icazəli texnika növləri, ASC sort.',
            'report_rows' => [
                'Unit name -> equipment_id',
                'Engine hours -> engine_hours',
                'parse_status',
                'report_date / project_id / ownership_type',
            ],
            'click' => 'Sətir drilldown detalına eyni period və unit konteksti ilə bağlanır.',
            'excel' => 'top-working-units export block=least-working ilə eyni sort və filteri istifadə edir.',
        ],
        [
            'key' => 'most-working',
            'title' => 'Top 20 çox işləyənlər',
            'purpose' => 'Seçilmiş periodda ən çox faktiki motosaatı olan 20 texnikanı göstərir.',
            'dashboard_block' => 'Ranking table',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'engine_hours_report_unit_days',
            'service' => 'TopWorkingUnitsService',
            'binding' => 'parse_status=ok, engine_hours >= 0, icazəli texnika növləri, DESC sort.',
            'report_rows' => [
                'Unit name -> equipment_id',
                'Engine hours -> engine_hours',
                'parse_status',
                'report_date / project_id / ownership_type',
            ],
            'click' => 'Sətir drilldown detalına eyni period və unit konteksti ilə bağlanır.',
            'excel' => 'top-working-units export block=most-working ilə eyni sort və filteri istifadə edir.',
        ],
        [
            'key' => 'geofence-analysis',
            'title' => 'Geofence Transferləri',
            'purpose' => 'Ev geozonasından çıxıb başqa layihə geozonasında olan texnikaları göstərir.',
            'dashboard_block' => 'Donut chart cari foreign layihə/geozona üzrə + sağ cədvəl',
            'wialon_report' => 'geozon api',
            'local_source' => 'unit_foreign_geofence_intervals',
            'service' => 'GeofenceViolationService, GeofenceReportViolationCalculator',
            'binding' => 'home_project_id və foreign_geofence_id intervaldan oxunur; layihə geofence ID-ləri geofences.wialon_geofence_id ilə bağlanır.',
            'report_rows' => [
                'Source group -> home_project_id / ownership_type',
                'Visited geofence -> foreign_geofence_id / foreign_project_id',
                'entered_at, left_at, last_position_at',
                'duration_seconds >= 3 saat',
            ],
            'click' => 'Sektor və ya cədvəl sətri current_geozone_key ilə modal açır; yalnız həmin foreign geozonanın texnikaları göstərilir.',
            'excel' => 'Excel GeofenceViolationService::exportRows ilə Dashboard/modal seçimini təkrarlayır.',
        ],
        [
            'key' => 'utilization-trend',
            'title' => 'İstifadə əmsalı',
            'purpose' => 'Seçilmiş period üzrə gündəlik utilization trendini göstərir.',
            'dashboard_block' => 'Trend chart',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'daily_fleet_statistics / equipment_daily_stats',
            'service' => 'DashboardService::getUtilizationTrend, DashboardService::getUtilizationTrendByOwnership',
            'binding' => 'Period, project_id və ownership filterləri ilə lokal gündəlik statistikalar oxunur.',
            'report_rows' => [
                'statistic_date',
                'worked_hours',
                'planned_hours',
                'utilization_percent',
            ],
            'click' => 'Trend nöqtəsi seçilmiş gün üçün drilldown kontekstini saxlayır.',
            'excel' => 'Dashboard export utilization-trend summary rows ilə çıxarılır.',
        ],
    ],
];
