<?php

return [
    'update_sections' => [
        'static_fleet' => [
            'title' => 'Struktur və texnika siyahısı',
            'dashboard_section' => null,
            'manual' => 'Parametrlər -> Texnikaları sinxronlaşdır',
            'auto' => 'Gündəlik 00:00 paketində texnika və geofence siyahısı yenilənir.',
            'wialon_command' => 'fleet:sync-units / fleet:sync-geofences',
            'local_tables' => 'equipments, equipment_types, projects, project_wialon_groups, geofences',
        ],
        'daily_averages' => [
            'title' => 'Orta motosaat / Orta yürüş',
            'dashboard_section' => 'daily_averages',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Orta motosaat göstəricisi / Orta yürüş göstəricisi',
            'auto' => 'Gündəlik 00:00-da dünənki və seçilmiş əvvəlki günlər yenilənir.',
            'wialon_command' => 'fleet:sync-report-stats + fleet:aggregate-daily',
            'local_tables' => 'equipment_daily_stats, daily_unit_aggregates',
        ],
        'top_working_units' => [
            'title' => 'Top 20 az işləyənlər / Top 20 çox işləyənlər',
            'dashboard_section' => 'top_working_units',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Top 20 az işləyənlər / Top 20 çox işləyənlər',
            'auto' => 'Gündəlik 00:00 paketində Wialon Engine hours report yenilənir.',
            'wialon_command' => 'fleet:sync-engine-hours-report',
            'local_tables' => 'engine_hours_report_unit_days, wialon_report_sync_items',
        ],
        'geofence_outside' => [
            'title' => 'Geofence Transferləri',
            'dashboard_section' => 'geofence_outside',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Geofence Transferləri',
            'auto' => 'Gündəlik 00:00 paketində dünənki geozon api intervalı yenilənir.',
            'wialon_command' => 'fleet:sync-geozon-api',
            'local_tables' => 'unit_foreign_geofence_intervals',
        ],
        'geofence_violations' => [
            'title' => 'Geofence Pozuntuları',
            'dashboard_section' => 'geofence_violations',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Geofence Pozuntuları',
            'auto' => 'Gündəlik 00:00 paketində dünənki “Geofence Pozuntuları api” hesabatı yenilənir.',
            'wialon_command' => 'fleet:sync-geofence-violations-report',
            'local_tables' => 'geofence_violation_report_rows',
        ],
        'efficiency' => [
            'title' => 'Effektivlik',
            'dashboard_section' => 'efficiency',
            'manual' => 'Tarixi məlumatların yenilənməsi -> Effektivlik.',
            'auto' => 'Gündəlik 00:00 paketində Engine hours effektivlik sinxronizasiyası növbəyə verilir.',
            'wialon_command' => 'fleet:queue-efficiency-sync',
            'local_tables' => 'efficiency_daily_facts, efficiency_sync_runs, efficiency_sync_tasks',
        ],
    ],

    'shared_bindings' => [
        [
            'title' => 'Project binding',
            'description' => 'Layihə və ownership Wialon qrupuna project_wialon_groups cədvəli ilə bağlanır.',
            'items' => [
                'projects.id -> project_wialon_groups.project_id',
                'project_wialon_groups.ownership_type -> NWC / ICARE',
                'project_wialon_groups.wialon_group_id -> Wialon qrup ID',
            ],
        ],
        [
            'title' => 'Geofence binding',
            'description' => 'Layihə geozonaları Wialon geofence ID ilə bağlanır. Bir layihədə bir neçə geofence ola bilər.',
            'items' => [
                'geofences.project_id -> projects.id',
                'geofences.wialon_geofence_id -> Wialon geofence ID',
                'Wialon geofence group istifadə olunmur',
            ],
        ],
        [
            'title' => 'Dashboard filters',
            'description' => 'Dashboard, modal və Excel eyni filter kontekstini istifadə etməlidir.',
            'items' => [
                'date_from / date_to',
                'project_id',
                'ownership_type',
                'equipment_type_id',
                'status / current_geozone_key',
            ],
        ],
    ],

    'widgets' => [
        [
            'key' => 'ownership-share',
            'title' => 'NWC və İCARƏ payı',
            'purpose' => 'Layihələrə bağlı texnikaların ownership üzrə say bölgüsünü göstərir.',
            'dashboard_block' => 'Donut chart + sağ legend',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, project_wialon_groups',
            'service' => 'FleetOwnershipStatsService, DashboardService::getOverview',
            'binding' => 'Yalnız layihələrə bağlı NWC / ICARE qrupları sayılır; +NWC+ və +İcarə+ root qrupları sayılmır.',
            'report_rows' => [
                'equipments.project_wialon_group_id',
                'equipments.matched_wialon_group_id',
                'equipments.ownership_type',
                'equipments.active / excluded_from_dashboard',
            ],
            'click' => 'Sektor kliklənəndə Dashboard drilldown modal ownership filteri ilə açılır.',
            'excel' => 'Dashboard export eyni ownership seçimini istifadə edir.',
        ],
        [
            'key' => 'equipment-types-nwc',
            'title' => 'Texnika növü üzrə: NWC payı',
            'purpose' => 'NWC texnikalarının növ üzrə sayını göstərir.',
            'dashboard_block' => 'Donut chart + növ cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, equipment_types',
            'service' => 'DashboardService::getEquipmentTypeDistributionByOwnership',
            'binding' => 'ownership_type = NWC, project_id filteri varsa yalnız seçilmiş layihə.',
            'report_rows' => [
                'equipment_types.name',
                'COUNT(DISTINCT equipments.id)',
                'equipments.project_id',
                'equipments.ownership_type',
            ],
            'click' => 'Növ sətri/sektoru drilldown modalı equipment_type_id + ownership_type=NWC ilə açır.',
            'excel' => 'equipment-types-nwc block export eyni növ və ownership məntiqini istifadə edir.',
        ],
        [
            'key' => 'equipment-types-icare',
            'title' => 'Texnika növü üzrə: İcarə payı',
            'purpose' => 'İcarə texnikalarının növ üzrə sayını göstərir.',
            'dashboard_block' => 'Donut chart + növ cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, equipment_types',
            'service' => 'DashboardService::getEquipmentTypeDistributionByOwnership',
            'binding' => 'ownership_type = ICARE, project_id filteri varsa yalnız seçilmiş layihə.',
            'report_rows' => [
                'equipment_types.name',
                'COUNT(DISTINCT equipments.id)',
                'equipments.project_id',
                'equipments.ownership_type',
            ],
            'click' => 'Növ sətri/sektoru drilldown modalı equipment_type_id + ownership_type=ICARE ilə açır.',
            'excel' => 'equipment-types-icare block export eyni növ və ownership məntiqini istifadə edir.',
        ],
        [
            'key' => 'project-comparison',
            'title' => 'Layihə üzrə: NWC və İcarə payı',
            'purpose' => 'Hər layihədə NWC və İcarə texnika sayını müqayisə edir.',
            'dashboard_block' => 'Horizontal bar chart + layihə cədvəli',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'equipments, projects',
            'service' => 'DashboardService::getProjectOwnershipComparison',
            'binding' => 'projects.id -> equipments.project_id; ownership_type üzrə iki say sütunu.',
            'report_rows' => [
                'projects.name',
                'COUNT(DISTINCT equipments.id) where ownership_type=NWC',
                'COUNT(DISTINCT equipments.id) where ownership_type=ICARE',
            ],
            'click' => 'Layihə seçimi cari Dashboard filtrlərini saxlayaraq modalda texnika növlərini göstərir; növ seçimi eyni layihə + ownership filtrləri ilə texnika siyahısını açır.',
            'excel' => 'Dashboard export layihə + ownership saylarını verir.',
        ],
        [
            'key' => 'project-work-categories-nwc',
            'title' => 'Effektivlik: NWC üzrə',
            'purpose' => 'NWC texnika-günlərini Engine hours üzrə beş statusda göstərir.',
            'dashboard_block' => 'Donut beş qarşılıqlı istisna statusun texnika-gün sayını göstərir.',
            'wialon_report' => 'Qrup report Engine hours (api)',
            'local_source' => 'efficiency_daily_facts',
            'service' => 'EfficiencyDashboardService',
            'binding' => 'project_wialon_groups.wialon_group_id üzrə Wialon qrup; ownership_type=NWC.',
            'report_rows' => [
                'Engine hours -> engine_hours_decimal və engine_seconds',
                'Hər obyekt + tarix yalnız bir əsas status alır',
                'Başlama, bitmə və yürüş audit üçün saxlanılır',
            ],
            'click' => 'Status kliklənəndə əvvəl layihələr NWC/İCARƏ/Say üzrə, sonra layihənin texnika jurnalı açılır.',
            'excel' => 'Excel Xülasə və Detallar vərəqlərini eyni lokal faktlardan çıxarır.',
        ],
        [
            'key' => 'project-work-categories-icare',
            'title' => 'Effektivlik: İcarə üzrə',
            'purpose' => 'İcarə texnika-günlərini Engine hours üzrə beş statusda göstərir.',
            'dashboard_block' => 'Donut beş qarşılıqlı istisna statusun texnika-gün sayını göstərir.',
            'wialon_report' => 'Qrup report Engine hours (api)',
            'local_source' => 'efficiency_daily_facts',
            'service' => 'EfficiencyDashboardService',
            'binding' => 'project_wialon_groups.wialon_group_id üzrə Wialon qrup; ownership_type=ICARE.',
            'report_rows' => [
                'Engine hours -> engine_hours_decimal və engine_seconds',
                'Hər obyekt + tarix yalnız bir əsas status alır',
                'Başlama, bitmə və yürüş audit üçün saxlanılır',
            ],
            'click' => 'Status kliklənəndə əvvəl layihələr NWC/İCARƏ/Say üzrə, sonra layihənin texnika jurnalı açılır.',
            'excel' => 'Excel Xülasə və Detallar vərəqlərini eyni lokal faktlardan çıxarır.',
        ],
        [
            'key' => 'average-engine-hours',
            'title' => 'Orta motosaat göstəricisi',
            'purpose' => 'Texnika növü və ownership üzrə gündəlik orta motosaatı göstərir.',
            'dashboard_block' => 'Horizontal average bars',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'DashboardDailyAverageService',
            'binding' => 'Layihə + ownership Wialon qrupundan Engine hours sütunu yerli statistikaya yazılır.',
            'report_rows' => [
                'Engine hours -> worked_hours / engine_hours',
                'Texnika adı -> equipment_id match',
                'statistic_date',
                'Formula: SUM(valid engine_hours) / COUNT(valid unit-day rows)',
                'Explicit data_available=false and invalid calculation statuses are excluded',
            ],
            'click' => 'Bar kliklənəndə metric=engine_hours, type, ownership və period ilə modal açılır.',
            'excel' => 'Xülasə və Gündəlik detallar eyni DashboardDailyAverageService seçimini istifadə edir.',
        ],
        [
            'key' => 'average-mileage',
            'title' => 'Orta yürüş göstəricisi',
            'purpose' => 'Dump Truck üçün ownership üzrə gündəlik orta yürüşü göstərir.',
            'dashboard_block' => 'Horizontal average bars',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'equipment_daily_stats',
            'service' => 'DashboardDailyAverageService',
            'binding' => 'Yalnız Dump Truck; mənfi mileage çıxarılır; NULL adi 0 kimi maskalanmır.',
            'report_rows' => [
                'Mileage / distance -> distance_km',
                'Texnika adı -> equipment_id match',
                'statistic_date',
                'Formula: SUM(valid distance_km) / COUNT(valid unit-day rows)',
                'Explicit data_available=false, negative mileage and invalid calculation statuses are excluded',
            ],
            'click' => 'Bar kliklənəndə metric=mileage, type=Dump Truck, ownership və period ilə modal açılır.',
            'excel' => 'Xülasə və Gündəlik detallar eyni DashboardDailyAverageService seçimini istifadə edir.',
        ],
        [
            'key' => 'least-working',
            'title' => 'Top 20 az işləyənlər',
            'purpose' => 'Seçilmiş periodda ən az faktiki motosaatı olan 20 texnikanı göstərir.',
            'dashboard_block' => 'Ranking table',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'engine_hours_report_unit_days',
            'service' => 'TopWorkingUnitsService',
            'binding' => 'parse_status=ok, engine_hours >= 0; yalnız Dump Truck, Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader və Road Roller; ASC sort.',
            'report_rows' => [
                'Unit name -> equipment_id',
                'Engine hours -> engine_hours',
                'parse_status',
                'report_date / project_id / ownership_type',
            ],
            'click' => 'Sətir drilldown detalına eyni period və unit konteksti ilə bağlanır.',
            'excel' => 'top-working-units export block=least-working ilə eyni sort və filteri istifadə edir.',
        ],
        [
            'key' => 'most-working',
            'title' => 'Top 20 çox işləyənlər',
            'purpose' => 'Seçilmiş periodda ən çox faktiki motosaatı olan 20 texnikanı göstərir.',
            'dashboard_block' => 'Ranking table',
            'wialon_report' => 'Engine hours: NWC vs İCARƏ (Api)',
            'local_source' => 'engine_hours_report_unit_days',
            'service' => 'TopWorkingUnitsService',
            'binding' => 'parse_status=ok, engine_hours >= 0; yalnız Dump Truck, Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader və Road Roller; DESC sort.',
            'report_rows' => [
                'Unit name -> equipment_id',
                'Engine hours -> engine_hours',
                'parse_status',
                'report_date / project_id / ownership_type',
            ],
            'click' => 'Sətir drilldown detalına eyni period və unit konteksti ilə bağlanır.',
            'excel' => 'top-working-units export block=most-working ilə eyni sort və filteri istifadə edir.',
        ],
        [
            'key' => 'geofence-analysis',
            'title' => 'Geofence Transferləri',
            'purpose' => 'Ev geozonasından çıxıb başqa layihə geozonasında olan texnikaları göstərir.',
            'dashboard_block' => 'Donut chart cari foreign layihə/geozona üzrə + sağ cədvəl',
            'wialon_report' => 'geozon api',
            'local_source' => 'unit_foreign_geofence_intervals',
            'service' => 'GeofenceViolationService, GeofenceReportViolationCalculator',
            'binding' => 'home_project_id və foreign_geofence_id intervaldan oxunur; layihə geofence ID-ləri geofences.wialon_geofence_id ilə bağlanır.',
            'report_rows' => [
                'Source group -> home_project_id / ownership_type',
                'Visited geofence -> foreign_geofence_id / foreign_project_id',
                'entered_at, left_at, last_position_at',
                'duration_seconds >= 3 saat',
            ],
            'click' => 'Sektor və ya cədvəl sətri current_geozone_key ilə modal açır; yalnız həmin foreign geozonanın texnikaları göstərilir.',
            'excel' => 'Excel GeofenceViolationService::exportRows ilə Dashboard/modal seçimini təkrarlayır.',
        ],
        [
            'key' => 'geofence-violations-report',
            'title' => 'Geofence Pozuntuları',
            'purpose' => 'Bütün layihə geozonalarından kənarda fasiləsiz 3 saatdan çox qalan icazəli texnikaları göstərir.',
            'dashboard_block' => 'Ayrı donut chart + layihə üzrə sağ legend',
            'wialon_report' => 'Geofence Pozuntuları api',
            'local_source' => 'geofence_violation_report_rows',
            'service' => 'GeofenceViolationsDashboardService, GeofenceViolationReportImporter',
            'binding' => 'Hesabat sətri equipment wialon_unit_id ilə bağlanır; yalnız ayrıca fasiləsiz interval müddəti 3 saatdan çox olduqda qəbul edilir.',
            'report_rows' => [
                'Out of geofences -> nested unit rows',
                'Unit name / Wialon unit ID',
                'Equipment type -> yalnız icazəli 7 növ',
                'Entry time -> exited_at',
                'Exit time / last confirmed position -> last_confirmed_at',
                'Duration must equal the continuous entry-exit span',
            ],
            'click' => 'Donut və legend sətri seçilmiş period və layihə filtrləri ilə pozuntu siyahısını modalda açır.',
            'excel' => 'Bu mərhələdə ayrıca Excel yoxdur; detallı cədvəl müstəqil modulda göstərilir.',
        ],
        [
            'key' => 'utilization-trend',
            'title' => 'İstifadə əmsalı',
            'purpose' => 'Seçilmiş period üzrə gündəlik utilization trendini göstərir.',
            'dashboard_block' => 'Trend chart',
            'wialon_report' => 'Birbaşa Wialon report istifadə etmir',
            'local_source' => 'daily_fleet_statistics / equipment_daily_stats',
            'service' => 'DashboardService::getUtilizationTrend, DashboardService::getUtilizationTrendByOwnership',
            'binding' => 'Period, project_id və ownership filterləri ilə lokal gündəlik statistikalar oxunur.',
            'report_rows' => [
                'statistic_date',
                'worked_hours',
                'planned_hours',
                'utilization_percent',
            ],
            'click' => 'Trend nöqtəsi seçilmiş gün üçün drilldown kontekstini saxlayır.',
            'excel' => 'Dashboard export utilization-trend summary rows ilə çıxarılır.',
        ],
    ],
];
