<?php

$catalogReport = 'Wialon hesabatı istifadə edilmir. Mənbə sinxronlaşdırılmış texnika kataloqudur.';
$dailyReport = 'Qrup date report Engine hours (api)';
$afterHoursReport = 'Qeyri iş saatlarında işləyən';
$monthlyReport = 'Report for Aylıq effektivlik; cədvəllər: Engine hours və Geofence. Obyekt qrupu: Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader, Road Roller, Dump Truck.';
$monthlyCalculation = [
    'D = seçilmiş gün sayı; MS = obyektin seçilmiş günlər üzrə Total Engine hours cəmi.',
    'Kritik aşağı: MS < D * 5 saat.',
    'Aşağı: D * 5 <= MS <= D * 7 saat; Normal: MS > D * 7 saat.',
];
$dailyEfficiencyCalculation = [
    'Məlumat yoxdur: motosaat <= 0; 0-1 saat: 0 < motosaat < 1.',
    '1-7 saat: 1 <= motosaat < 7; 7-10 saat: 7 <= motosaat <= 10.',
    '10 saatdan artıq: motosaat > 10.',
];

return [
    'groups' => [
        'overview' => [
            'title' => 'Ümumi baxış',
            'route' => '/dashboard?tab=overview',
            'blocks' => [
                [
                    'key' => 'ownership-share',
                    'title' => 'NWC və İCARƏ payı',
                    'report' => $catalogReport,
                    'local_source' => 'equipments, project_wialon_groups',
                    'project_rule' => 'Texnika layihəyə project_wialon_groups vasitəsilə bağlanır. Yalnız aktiv, Dashboard-da görünən və layihə Wialon qrupuna bağlı texnika qəbul edilir.',
                    'period_rule' => 'Tarix intervalı bu bloka təsir etmir; layihə, texnika növü və mənsubiyyət filtrləri tətbiq edilir.',
                    'calculation' => [
                        'NWC sayı = unikal NWC wialon_unit_id sayı.',
                        'İCARƏ sayı = unikal ICARE wialon_unit_id sayı.',
                        'Pay = mənsubiyyət sayı / (NWC + İCARƏ) * 100.',
                    ],
                    'result' => 'Donut hər mənsubiyyət üzrə unikal texnika sayını və faizini göstərir.',
                ],
                [
                    'key' => 'equipment-types-nwc',
                    'title' => 'Texnika növü üzrə: NWC',
                    'report' => $catalogReport,
                    'local_source' => 'equipments, equipment_types, project_wialon_groups',
                    'project_rule' => 'ownership_type = NWC. Texnika aktiv, Dashboard-da görünən və layihə Wialon qrupuna bağlı olmalıdır.',
                    'period_rule' => 'Tarix intervalı təsir etmir; seçilmiş layihə və texnika növü filtrləri tətbiq edilir.',
                    'calculation' => [
                        'Hər equipment_types.name üzrə texnika sayı hesablanır.',
                        'Eyni texnika siyahıda yalnız bir dəfə sayılır.',
                        'Faiz = növ üzrə say / bütün NWC texnikaları * 100.',
                    ],
                    'result' => 'NWC parkının texnika növləri üzrə say və faiz bölgüsü.',
                ],
                [
                    'key' => 'equipment-types-icare',
                    'title' => 'Texnika növü üzrə: İCARƏ',
                    'report' => $catalogReport,
                    'local_source' => 'equipments, equipment_types, project_wialon_groups',
                    'project_rule' => 'ownership_type = ICARE. Texnika aktiv, Dashboard-da görünən və layihə Wialon qrupuna bağlı olmalıdır.',
                    'period_rule' => 'Tarix intervalı təsir etmir; seçilmiş layihə və texnika növü filtrləri tətbiq edilir.',
                    'calculation' => [
                        'Hər equipment_types.name üzrə texnika sayı hesablanır.',
                        'Eyni texnika siyahıda yalnız bir dəfə sayılır.',
                        'Faiz = növ üzrə say / bütün İCARƏ texnikaları * 100.',
                    ],
                    'result' => 'İCARƏ parkının texnika növləri üzrə say və faiz bölgüsü.',
                ],
                [
                    'key' => 'project-comparison',
                    'title' => 'Layihə üzrə NWC və İCARƏ',
                    'report' => $catalogReport,
                    'local_source' => 'equipments, projects, project_wialon_groups',
                    'project_rule' => 'Layihə equipments.project_id və ona bağlı project_wialon_groups qeydi ilə müəyyən edilir.',
                    'period_rule' => 'Tarix intervalı təsir etmir; aktiv Dashboard texnikaları cari kataloq vəziyyətinə görə sayılır.',
                    'calculation' => [
                        'Hər layihə üzrə NWC texnikalarının sayı ayrı hesablanır.',
                        'Hər layihə üzrə İCARƏ texnikalarının sayı ayrı hesablanır.',
                        'Cəmi = NWC sayı + İCARƏ sayı.',
                    ],
                    'result' => 'Hər layihə üzrə NWC, İCARƏ və ümumi texnika sayı.',
                ],
                [
                    'key' => 'utilization-trend',
                    'title' => 'İstifadə əmsalı',
                    'report' => $dailyReport,
                    'local_source' => 'equipment_daily_stats',
                    'project_rule' => 'Hesabat layihənin NWC/İCARƏ Wialon qrupları üzrə yığılır; Layihəsiz və Təmir əməliyyat Dashboard-undan xaric edilir.',
                    'period_rule' => 'Yalnız seçilmiş tarix intervalındakı equipment_daily_stats sətirləri istifadə edilir.',
                    'calculation' => [
                        'Texnika-gün istifadə faizi = min(100, motosaat / planned_daily_hours * 100).',
                        'Günlük NWC və İCARƏ nəticəsi = həmin günün utilization_percent orta qiyməti.',
                        'Məlumat olmayan tarix qrafikdə 0 kimi göstərilir.',
                    ],
                    'result' => 'Seçilmiş dövr üzrə NWC və İCARƏ günlük istifadə faizi trendi.',
                ],
            ],
        ],
        'efficiency' => [
            'title' => 'Effektivlik',
            'route' => '/dashboard?tab=efficiency',
            'blocks' => [
                [
                    'key' => 'monthly-efficiency-nwc',
                    'title' => 'Aylıq effektivlik - NWC üzrə',
                    'report' => $monthlyReport,
                    'local_source' => 'monthly_efficiency_unit_geofence_facts',
                    'project_rule' => 'Yalnız NWC texnikaları qəbul edilir. Texnikanın layihəsi project_wialon_groups üzrə müəyyən edilir; Layihəsiz və Təmir tam xaric edilir.',
                    'period_rule' => 'Yalnız seçilmiş date_from-date_to günləri cəmlənir. Hər obyekt/gün bir dəfə sayılır.',
                    'calculation' => $monthlyCalculation,
                    'result' => 'Statuslar unikal NWC texnikası üzrə hesablanır; faiz = statusdakı texnika / bütün NWC texnikaları * 100.',
                ],
                [
                    'key' => 'monthly-efficiency-icare',
                    'title' => 'Aylıq effektivlik - İCARƏ üzrə',
                    'report' => $monthlyReport,
                    'local_source' => 'monthly_efficiency_unit_geofence_facts',
                    'project_rule' => 'Yalnız İCARƏ texnikaları qəbul edilir. Texnikanın layihəsi project_wialon_groups üzrə müəyyən edilir; Layihəsiz və Təmir tam xaric edilir.',
                    'period_rule' => 'Yalnız seçilmiş date_from-date_to günləri cəmlənir. Hər obyekt/gün bir dəfə sayılır.',
                    'calculation' => $monthlyCalculation,
                    'result' => 'Statuslar unikal İCARƏ texnikası üzrə hesablanır; faiz = statusdakı texnika / bütün İCARƏ texnikaları * 100.',
                ],
                [
                    'key' => 'project-work-categories-nwc',
                    'title' => 'Effektivlik: NWC üzrə 24 saat',
                    'report' => $dailyReport,
                    'local_source' => 'efficiency_daily_facts',
                    'project_rule' => 'Hesabat hər layihənin NWC project_wialon_groups qeydi üzrə icra edilir. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Hesablama vahidi texnika-gündür. Dublikat olduqda business_date + project_id + wialon_unit_id üzrə ən son fakt götürülür.',
                    'calculation' => $dailyEfficiencyCalculation,
                    'result' => 'Hər status üzrə NWC texnika-gün sayı və payı.',
                ],
                [
                    'key' => 'project-work-categories-icare',
                    'title' => 'Effektivlik: İCARƏ üzrə 24 saat',
                    'report' => $dailyReport,
                    'local_source' => 'efficiency_daily_facts',
                    'project_rule' => 'Hesabat hər layihənin İCARƏ project_wialon_groups qeydi üzrə icra edilir. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Hesablama vahidi texnika-gündür. Dublikat olduqda business_date + project_id + wialon_unit_id üzrə ən son fakt götürülür.',
                    'calculation' => $dailyEfficiencyCalculation,
                    'result' => 'Hər status üzrə İCARƏ texnika-gün sayı və payı.',
                ],
                [
                    'key' => 'after-hours-nwc',
                    'title' => 'Qeyri iş saatlarında işləyən: NWC',
                    'report' => $afterHoursReport,
                    'local_source' => 'night_day_efficiency_daily_facts',
                    'project_rule' => 'Ümumi effektivlik ilə eyni qayda: aktiv, Dashboard-da görünən, uyğun project_wialon_groups NWC qrupuna bağlı və icazəli texnika növləri. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Yalnız seçilmiş günlər və 00:00-07:59, 18:01-23:59 intervalları. Yalnız bu modulun dəqiq mənbə hesabatına uyğun sətirlər istifadə edilir.',
                    'calculation' => $dailyEfficiencyCalculation,
                    'result' => 'Seçilmiş dövrdə qeyri iş saatlarında işləyən NWC texnikaları motosaat intervalına görə qruplaşdırılır.',
                ],
                [
                    'key' => 'after-hours-icare',
                    'title' => 'Qeyri iş saatlarında işləyən: İCARƏ',
                    'report' => $afterHoursReport,
                    'local_source' => 'night_day_efficiency_daily_facts',
                    'project_rule' => 'Ümumi effektivlik ilə eyni qayda: aktiv, Dashboard-da görünən, uyğun project_wialon_groups İCARƏ qrupuna bağlı və icazəli texnika növləri. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Yalnız seçilmiş günlər və 00:00-07:59, 18:01-23:59 intervalları. Yalnız bu modulun dəqiq mənbə hesabatına uyğun sətirlər istifadə edilir.',
                    'calculation' => $dailyEfficiencyCalculation,
                    'result' => 'Seçilmiş dövrdə qeyri iş saatlarında işləyən İCARƏ texnikaları motosaat intervalına görə qruplaşdırılır.',
                ],
                [
                    'key' => 'average-engine-hours',
                    'title' => 'Orta motosaat göstəricisi',
                    'report' => $dailyReport,
                    'local_source' => 'equipment_daily_stats',
                    'project_rule' => 'Layihə və mənsubiyyət project_wialon_groups üzrədir. Növlər: Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader, Road Roller.',
                    'period_rule' => 'Yalnız seçilmiş tarix intervalında success/ok/published statuslu və data_available != false texnika-gün sətirləri qəbul edilir.',
                    'calculation' => [
                        'Ümumi motosaat = etibarlı worked_hours cəmi.',
                        'Etibarlı texnika-gün = motosaat məlumatı olan sətir sayı.',
                        'Orta motosaat = ümumi motosaat / etibarlı texnika-gün sayı.',
                    ],
                    'result' => 'Texnika növü və mənsubiyyət üzrə bir texnikanın bir günə düşən orta motosaatı.',
                ],
                [
                    'key' => 'average-mileage',
                    'title' => 'Orta yürüş göstəricisi',
                    'report' => $dailyReport.', Mileage sütunu',
                    'local_source' => 'equipment_daily_stats',
                    'project_rule' => 'Layihə və mənsubiyyət project_wialon_groups üzrədir. Yalnız Dump Truck qəbul edilir.',
                    'period_rule' => 'Yalnız seçilmiş tarix intervalında etibarlı, data_available != false və distance_km >= 0 olan texnika-gün sətirləri qəbul edilir.',
                    'calculation' => [
                        'Ümumi yürüş = etibarlı distance_km cəmi.',
                        'Etibarlı texnika-gün = yürüş məlumatı olan sətir sayı.',
                        'Orta yürüş = ümumi yürüş / etibarlı texnika-gün sayı.',
                    ],
                    'result' => 'NWC və İCARƏ Dump Truck üzrə bir texnikanın bir günə düşən orta yürüşü.',
                ],
            ],
        ],
        'geozones' => [
            'title' => 'Geozonalar',
            'route' => '/dashboard?tab=geozones',
            'blocks' => [
                [
                    'key' => 'geofence-analysis',
                    'title' => 'Geofence Transferləri',
                    'report' => 'Geofence Transferləri api',
                    'local_source' => 'unit_foreign_geofence_intervals, geofences, projects',
                    'project_rule' => 'Ev layihəsi texnikanın project_wialon_groups bağlılığıdır; cari layihə koordinatı saxlayan aktiv layihə geozonasıdır. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Seçilmiş dövrlə kəsişən intervallar götürülür. Standart minimum müddət 180 dəqiqədir; köhnə açıq mövqe intervalı göstərilmir.',
                    'calculation' => [
                        'Yalnız texnika ev layihəsindən fərqli aktiv layihə geozonasında olduqda interval qəbul edilir.',
                        'Eyni ev və cari layihə, qeyri-müəyyən geozona və ambiguous uyğunluq xaric edilir.',
                        'Növlər: Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader, Road Roller, Dump Truck.',
                    ],
                    'result' => 'Texnikanın ev layihəsindən hansı xarici layihə geozonasına keçdiyini və orada qalma müddətini göstərir.',
                ],
                [
                    'key' => 'geofence-violations-report',
                    'title' => 'Geofence Pozuntuları',
                    'report' => 'Geofence Pozuntuları api',
                    'local_source' => 'geofence_violation_report_rows',
                    'project_rule' => 'Layihə hesabat sətrinin project_id bağlılığından götürülür; aktiv layihə, icazəli Wialon qrupu və Dashboard texnikası olmalıdır. Layihəsiz və Təmir xaric edilir.',
                    'period_rule' => 'Pozuntu intervalı seçilmiş dövrlə kəsişməlidir: exited_at <= dövrün sonu və last_confirmed_at >= dövrün başlanğıcı.',
                    'calculation' => [
                        'Yalnız bütün layihə geozonalarından kənarda qalma müddəti 10 800 saniyədən çox olan sətirlər qəbul edilir.',
                        'last_confirmed_at exited_at vaxtından əvvəl ola bilməz; hesabat dövrü və vaxtlar boş ola bilməz.',
                        'Növlər: Bulldozer, Excavator, Loader, Backhoe Loader, Road Grader, Road Roller, Dump Truck.',
                    ],
                    'result' => 'Ümumi pozuntu sayı, aktiv pozuntuda olan unikal texnika, layihə bölgüsü və ən uzun pozuntu müddəti.',
                ],
            ],
        ],
    ],
];
