<?php

use App\Support\FleetVehicleType;

return [
    'wialon' => [
        'base_url' => env('WIALON_BASE_URL', 'https://hst-api.wialon.com'),
        'token' => env('WIALON_TOKEN'),
        'timeout' => (int) env('WIALON_TIMEOUT', 30),
        'session_cache_minutes' => (int) env('WIALON_CACHE_SESSION_MINUTES', 30),
        'report_timezone_offset' => (int) env('WIALON_REPORT_TIMEZONE_OFFSET', 134232128),
        'report_language' => env('WIALON_REPORT_LANGUAGE', 'ru'),
        'report_status_attempts' => (int) env('WIALON_REPORT_STATUS_ATTEMPTS', 300),
        'report_status_delay_ms' => (int) env('WIALON_REPORT_STATUS_DELAY_MS', 1000),
        'report_rows_attempts' => (int) env('WIALON_REPORT_ROWS_ATTEMPTS', 6),
        'report_rows_delay_ms' => (int) env('WIALON_REPORT_ROWS_DELAY_MS', 1000),
        'engine_hours_report_resource_id' => (int) env('WIALON_ENGINE_HOURS_REPORT_RESOURCE_ID', 601701680),
        'engine_hours_report_template_id' => (int) env('WIALON_ENGINE_HOURS_REPORT_TEMPLATE_ID', 9),
        'engine_hours_report_template_name' => env('WIALON_ENGINE_HOURS_REPORT_TEMPLATE_NAME', 'Engine hours: NWC vs İCARƏ (Api)'),
        'engine_hours_report_cache_minutes' => (int) env('WIALON_ENGINE_HOURS_REPORT_CACHE_MINUTES', 30),
        'engine_hours_report_timeout' => (int) env('WIALON_ENGINE_HOURS_REPORT_TIMEOUT', 15),
        'engine_hours_report_chunk_size' => (int) env('WIALON_ENGINE_HOURS_REPORT_CHUNK_SIZE', 500),
        'engine_hours_report_interval_flags' => (int) env('WIALON_ENGINE_HOURS_REPORT_INTERVAL_FLAGS', 0),
        'engine_hours_report_nested_depth' => (int) env('WIALON_ENGINE_HOURS_REPORT_NESTED_DEPTH', 2),
        'engine_hours_sync_lock_seconds' => (int) env('WIALON_ENGINE_HOURS_SYNC_LOCK_SECONDS', 900),
        'efficiency_report_resource_id' => (int) env('WIALON_EFFICIENCY_REPORT_RESOURCE_ID', 601701680),
        'efficiency_report_template_id' => (int) env('WIALON_EFFICIENCY_REPORT_TEMPLATE_ID', 19),
        'efficiency_report_template_name' => env('WIALON_EFFICIENCY_REPORT_TEMPLATE_NAME', 'Qrup report Engine hours (api)'),
        'efficiency_report_timeout' => (int) env('WIALON_EFFICIENCY_REPORT_TIMEOUT', 90),
        'efficiency_report_chunk_size' => (int) env('WIALON_EFFICIENCY_REPORT_CHUNK_SIZE', 500),
        'efficiency_sync_lock_seconds' => (int) env('WIALON_EFFICIENCY_SYNC_LOCK_SECONDS', 1800),
        'daily_engine_hours_report_timeout' => (int) env('WIALON_DAILY_ENGINE_HOURS_REPORT_TIMEOUT', 30),
        'report_stats_sync_timeout' => (int) env('WIALON_REPORT_STATS_SYNC_TIMEOUT', 90),
        'auto_sync_max_batches' => (int) env('WIALON_AUTO_SYNC_MAX_BATCHES', 100),
        'checkpoint_retention_days' => (int) env('WIALON_CHECKPOINT_RETENTION_DAYS', 90),
        'geofence_outside_report_resource_id' => (int) env('WIALON_GEOFENCE_OUTSIDE_REPORT_RESOURCE_ID', env('WIALON_ENGINE_HOURS_REPORT_RESOURCE_ID', 601701680)),
        'geofence_outside_report_template_id' => (int) env('WIALON_GEOFENCE_OUTSIDE_REPORT_TEMPLATE_ID', 0),
        'geofence_outside_report_template_name' => env('WIALON_GEOFENCE_OUTSIDE_REPORT_TEMPLATE_NAME', 'Dashboard geofence outside (Api)'),
        'geofence_outside_report_cache_minutes' => (int) env('WIALON_GEOFENCE_OUTSIDE_REPORT_CACHE_MINUTES', 30),
        'geofence_outside_report_timeout' => (int) env('WIALON_GEOFENCE_OUTSIDE_REPORT_TIMEOUT', 10),
        'geozon_report_resource_id' => (int) env('WIALON_GEOZON_REPORT_RESOURCE_ID', env('WIALON_ENGINE_HOURS_REPORT_RESOURCE_ID', 601701680)),
        'geozon_report_template_id' => (int) env('WIALON_GEOZON_REPORT_TEMPLATE_ID', 0),
        'geozon_report_template_name' => env('WIALON_GEOZON_REPORT_TEMPLATE_NAME', 'Geofence Transferləri api'),
        'geozon_report_timeout' => (int) env('WIALON_GEOZON_REPORT_TIMEOUT', 30),
        'geozon_report_chunk_size' => (int) env('WIALON_GEOZON_REPORT_CHUNK_SIZE', 500),
        'geozon_report_interval_flags' => (int) env('WIALON_GEOZON_REPORT_INTERVAL_FLAGS', 0),
        'geozon_report_sleep_ms' => (int) env('WIALON_GEOZON_REPORT_SLEEP_MS', 250),
        'report_session_lock_key' => env('WIALON_REPORT_SESSION_LOCK_KEY', 'wialon-report-session'),
        'report_session_lock_seconds' => (int) env('WIALON_REPORT_SESSION_LOCK_SECONDS', 300),
        'report_session_lock_wait_seconds' => (int) env('WIALON_REPORT_SESSION_LOCK_WAIT_SECONDS', 300),
        'report_period_grace_hours' => (int) env('WIALON_REPORT_PERIOD_GRACE_HOURS', 6),
        'daily_report_fallback_max_days' => (int) env('WIALON_DAILY_REPORT_FALLBACK_MAX_DAYS', 3),
        'daily_report_fallback_max_reports' => (int) env('WIALON_DAILY_REPORT_FALLBACK_MAX_REPORTS', 14),
        'live_dashboard_reports' => (bool) env('WIALON_LIVE_DASHBOARD_REPORTS', false),
        'nwc_group_id' => (string) env('WIALON_NWC_GROUP_ID', '601701870'),
        'icare_group_id' => (string) env('WIALON_ICARE_GROUP_ID', '601701871'),
    ],

    'dashboard' => [
        'cache_minutes' => (int) env('DASHBOARD_CACHE_MINUTES', 10),
        'cache_lock_seconds' => (int) env('DASHBOARD_CACHE_LOCK_SECONDS', 30),
        'cache_lock_wait_seconds' => (int) env('DASHBOARD_CACHE_LOCK_WAIT_SECONDS', 5),
        'export_queue_threshold_rows' => (int) env('DASHBOARD_EXPORT_QUEUE_THRESHOLD_ROWS', 5000),
        'slow_generation_ms' => (int) env('DASHBOARD_SLOW_GENERATION_MS', 5000),
        'performance_logging_enabled' => (bool) env('DASHBOARD_PERFORMANCE_LOGGING_ENABLED', false),
        'slow_request_ms' => (int) env('DASHBOARD_SLOW_REQUEST_MS', 3000),
        'max_period_days' => (int) env('DASHBOARD_MAX_PERIOD_DAYS', 366),
        'modal_max_period_days' => (int) env('DASHBOARD_MODAL_MAX_PERIOD_DAYS', 92),
        'export_max_period_days' => (int) env('DASHBOARD_EXPORT_MAX_PERIOD_DAYS', 366),
        'export_sync_max_days' => (int) env('DASHBOARD_EXPORT_SYNC_MAX_DAYS', 31),
        'export_disk' => env('DASHBOARD_EXPORT_DISK', 'dashboard_exports'),
        'export_retention_hours' => (int) env('DASHBOARD_EXPORT_RETENTION_HOURS', 24),
        'reversed_date_range_mode' => env('DASHBOARD_REVERSED_DATE_RANGE_MODE', 'swap'),
    ],

    'geofence' => [
        'min_exit_minutes' => (int) env('GEOFENCE_MIN_EXIT_MINUTES', 3),
    ],

    'foreign_geofence' => [
        'min_minutes' => (int) env('FOREIGN_GEOFENCE_MINUTES', 180),
        'show_all' => (bool) env('FOREIGN_GEOFENCE_SHOW_ALL', false),
        'include_stale' => (bool) env('FOREIGN_GEOFENCE_INCLUDE_STALE', false),
        'stale_after_minutes' => (int) env('FOREIGN_GEOFENCE_STALE_AFTER_MINUTES', 30),
        'merge_gap_minutes' => (int) env('GEOFENCE_VISIT_MERGE_GAP_MINUTES', 5),
        'geozon_api_sync_lookback_hours' => (int) env('GEOZON_API_SYNC_LOOKBACK_HOURS', 24),
        'geozon_api_max_concurrent_jobs' => (int) env('GEOZON_API_MAX_CONCURRENT_JOBS', 1),
        'allowed_vehicle_types' => FleetVehicleType::names(FleetVehicleType::FOREIGN_GEOFENCE_TYPES),
    ],

    'demo' => [
        'seed' => (bool) env('SEED_DEMO_DATA', false),
    ],
];
